apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.dockerImage }}
          imagePullPolicy: Always
          ports:
            - containerPort: 87
          livenessProbe:
            httpGet:
              path: /health
              port: 87
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 87
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
